/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as Char123LocaleChar125ContactRouteImport } from './routes/{-$locale}/contact'
import { Route as Char123LocaleChar125ExperienceRouteImport } from './routes/{-$locale}/experience'
import { Route as Char123LocaleChar125ResumeRouteImport } from './routes/{-$locale}/resume'
import { Route as Char123LocaleChar125StackRouteImport } from './routes/{-$locale}/stack'
import { Route as Char123LocaleChar125ProjectsIndexRouteImport } from './routes/{-$locale}/projects/index'
import { Route as Char123LocaleChar125ProjectsSlugRouteImport } from './routes/{-$locale}/projects/$slug'

const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/{-$locale}/',
    path: '/{-$locale}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/{-$locale}/about',
    path: '/{-$locale}/about',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ContactRoute =
  Char123LocaleChar125ContactRouteImport.update({
    id: '/{-$locale}/contact',
    path: '/{-$locale}/contact',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ExperienceRoute =
  Char123LocaleChar125ExperienceRouteImport.update({
    id: '/{-$locale}/experience',
    path: '/{-$locale}/experience',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ResumeRoute =
  Char123LocaleChar125ResumeRouteImport.update({
    id: '/{-$locale}/resume',
    path: '/{-$locale}/resume',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125StackRoute =
  Char123LocaleChar125StackRouteImport.update({
    id: '/{-$locale}/stack',
    path: '/{-$locale}/stack',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ProjectsIndexRoute =
  Char123LocaleChar125ProjectsIndexRouteImport.update({
    id: '/{-$locale}/projects/',
    path: '/{-$locale}/projects/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char123LocaleChar125ProjectsSlugRoute =
  Char123LocaleChar125ProjectsSlugRouteImport.update({
    id: '/{-$locale}/projects/$slug',
    path: '/{-$locale}/projects/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/experience': typeof Char123LocaleChar125ExperienceRoute
  '/{-$locale}/resume': typeof Char123LocaleChar125ResumeRoute
  '/{-$locale}/stack': typeof Char123LocaleChar125StackRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/projects/$slug': typeof Char123LocaleChar125ProjectsSlugRoute
  '/{-$locale}/projects/': typeof Char123LocaleChar125ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/experience': typeof Char123LocaleChar125ExperienceRoute
  '/{-$locale}/resume': typeof Char123LocaleChar125ResumeRoute
  '/{-$locale}/stack': typeof Char123LocaleChar125StackRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/projects/$slug': typeof Char123LocaleChar125ProjectsSlugRoute
  '/{-$locale}/projects': typeof Char123LocaleChar125ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/{-$locale}/contact': typeof Char123LocaleChar125ContactRoute
  '/{-$locale}/experience': typeof Char123LocaleChar125ExperienceRoute
  '/{-$locale}/resume': typeof Char123LocaleChar125ResumeRoute
  '/{-$locale}/stack': typeof Char123LocaleChar125StackRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/projects/$slug': typeof Char123LocaleChar125ProjectsSlugRoute
  '/{-$locale}/projects/': typeof Char123LocaleChar125ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/experience'
    | '/{-$locale}/resume'
    | '/{-$locale}/stack'
    | '/{-$locale}/'
    | '/{-$locale}/projects/$slug'
    | '/{-$locale}/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/experience'
    | '/{-$locale}/resume'
    | '/{-$locale}/stack'
    | '/{-$locale}'
    | '/{-$locale}/projects/$slug'
    | '/{-$locale}/projects'
  id:
    | '__root__'
    | '/{-$locale}/about'
    | '/{-$locale}/contact'
    | '/{-$locale}/experience'
    | '/{-$locale}/resume'
    | '/{-$locale}/stack'
    | '/{-$locale}/'
    | '/{-$locale}/projects/$slug'
    | '/{-$locale}/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125ContactRoute: typeof Char123LocaleChar125ContactRoute
  Char123LocaleChar125ExperienceRoute: typeof Char123LocaleChar125ExperienceRoute
  Char123LocaleChar125ResumeRoute: typeof Char123LocaleChar125ResumeRoute
  Char123LocaleChar125StackRoute: typeof Char123LocaleChar125StackRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125ProjectsSlugRoute: typeof Char123LocaleChar125ProjectsSlugRoute
  Char123LocaleChar125ProjectsIndexRoute: typeof Char123LocaleChar125ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/{-$locale}'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/{-$locale}/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/contact': {
      id: '/{-$locale}/contact'
      path: '/{-$locale}/contact'
      fullPath: '/{-$locale}/contact'
      preLoaderRoute: typeof Char123LocaleChar125ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/experience': {
      id: '/{-$locale}/experience'
      path: '/{-$locale}/experience'
      fullPath: '/{-$locale}/experience'
      preLoaderRoute: typeof Char123LocaleChar125ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/resume': {
      id: '/{-$locale}/resume'
      path: '/{-$locale}/resume'
      fullPath: '/{-$locale}/resume'
      preLoaderRoute: typeof Char123LocaleChar125ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/stack': {
      id: '/{-$locale}/stack'
      path: '/{-$locale}/stack'
      fullPath: '/{-$locale}/stack'
      preLoaderRoute: typeof Char123LocaleChar125StackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/projects/': {
      id: '/{-$locale}/projects/'
      path: '/{-$locale}/projects'
      fullPath: '/{-$locale}/projects/'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/projects/$slug': {
      id: '/{-$locale}/projects/$slug'
      path: '/{-$locale}/projects/$slug'
      fullPath: '/{-$locale}/projects/$slug'
      preLoaderRoute: typeof Char123LocaleChar125ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125ContactRoute: Char123LocaleChar125ContactRoute,
  Char123LocaleChar125ExperienceRoute: Char123LocaleChar125ExperienceRoute,
  Char123LocaleChar125ResumeRoute: Char123LocaleChar125ResumeRoute,
  Char123LocaleChar125StackRoute: Char123LocaleChar125StackRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125ProjectsSlugRoute: Char123LocaleChar125ProjectsSlugRoute,
  Char123LocaleChar125ProjectsIndexRoute:
    Char123LocaleChar125ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
